# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01edf9d9f0ad9c5fb98b58c2ae852a4a1d5a6a108af8ec90533e094375c001675b652d2e34f72e88eff8b02bb3d79cb5e0169ac99179dfa701990ff087286041

test:
  secret_key_base: 1c3553e647c865330a8ccbfa2552faf3abaf7a6300777df0ac27b25de64c47d55ae97dbb269652d557325272e23a095fb1d73d2ee5840bd7728c7c54992c1c58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
